#!/usr/bin/env bash
# scripts/treedx-local.sh — the TreeDX dev loop for dsh-chapters (docs/development.md § TreeDX).
#
#   scripts/treedx-local.sh up       build + boot dev-auth TreeDX on 127.0.0.1:4000, wait healthy
#   scripts/treedx-local.sh down     stop (keep the data volume; -v to wipe: down -v)
#   scripts/treedx-local.sh status   health + auth mode + whoami
#   scripts/treedx-local.sh token    mint a dev token; prints exports, writes var/treedx-dev.env
#   scripts/treedx-local.sh smoke    the six-step transport walk (repo→workspace→write→commit→read→search)
#   scripts/treedx-local.sh logs     follow container logs (first boot compiles the Rust NIF — minutes)
#
# Every fact this script assumes about the API is pinned by tests/integration/treedx-stub-server.ts
# and re-checked live by tests/integration/treedx-live.test.ts (which consumes var/treedx-dev.env).
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="$HERE/dev/treedx.compose.yaml"
ENV_FILE="$HERE/var/treedx-dev.env"
BASE="${TREEDX_LOCAL_BASE:-http://127.0.0.1:4000}"
SRC="$HERE/examples/treedx"

die() { echo "treedx-local: $*" >&2; exit 1; }

preflight() {
  command -v docker >/dev/null 2>&1 || die "docker is not installed. The TreeDX dev loop needs it (see docs/development.md § TreeDX dev loop)."
  docker info >/dev/null 2>&1 || die "the docker DAEMON is not running. Start it (e.g. 'systemctl start docker' — may need sudo), then re-run: $0 up"
  [ -f "$SRC/Dockerfile" ] || die "no TreeDX checkout at $SRC. It is gitignored (examples/ are reference clones); clone treeseed-ai/treedx there first."
}

# token/smoke/status need only the HTTP endpoint (NOT the docker CLI): an
# agent sandbox may reach the published port while the daemon socket sits
# behind group permissions its process lacks (measured 2026-09-21).
preflight_http() {
  [ -n "$(health)" ] || die "no TreeDX at $BASE — run '$0 up' (from a shell that can reach the docker daemon), or set TREEDX_LOCAL_BASE"
}

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }

health() { curl -fsS --max-time 3 "$BASE/api/v1/health" 2>/dev/null || true; }

wait_healthy() {
  local deadline=$(( $(date +%s) + ${TREEDX_LOCAL_WAIT_S:-1800} ))
  echo "waiting for $BASE/api/v1/health … (first boot compiles Rust NIF + Elixir deps; hours later boots are fast)"
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if [ -n "$(health)" ]; then echo "healthy: $(health)"; return 0; fi
    sleep 5
  done
  die "TreeDX did not become healthy within the window. Check: $0 logs"
}

cmd_up() {
  preflight
  compose up -d --build treedx-api
  wait_healthy
  echo
  echo "TreeDX is up. Next: $0 token   (then: $0 smoke)"
}

cmd_down() {
  preflight
  compose down "${@:2}"
}

cmd_status() {
  preflight_http
  echo "health:  $(health || echo UNREACHABLE)"
  echo "auth:    $(curl -fsS --max-time 3 "$BASE/api/v1/auth/mode" 2>/dev/null || echo UNREACHABLE)"
}

cmd_token() {
  preflight_http
  local body tok
  body=$(curl -fsS -X POST "$BASE/api/v1/auth/dev-token" -H 'content-type: application/json' \
    -d '{"actorId":"actor_demo","tenantId":"tenant_demo","expiresInSeconds":2592000}') \
    || die "dev-token mint failed — is the server up ($0 up) and in dev auth mode ($0 status)?"
  tok=$(echo "$body" | jq -er '.accessToken // .access_token // empty') || die "no accessToken in response: $body"
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    echo "# generated by scripts/treedx-local.sh token — gitignored (var/); do not commit"
    echo "TREEDX_LIVE_URL=$BASE"
    echo "TREEDX_LIVE_TOKEN=$tok"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "token minted (actor_demo/tenant_demo, 30d) — stored in $ENV_FILE (0600)"
  echo "export TREEDX_LIVE_URL=$BASE"
  echo "export TREEDX_LIVE_TOKEN=$tok"
}

cmd_smoke() {
  preflight_http
  [ -f "$ENV_FILE" ] || { cmd_token; }
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  local A="$TREEDX_LIVE_URL/api/v1" H_A=(-H "authorization: Bearer $TREEDX_LIVE_TOKEN") J=(-H 'content-type: application/json')
  local repo ws sha
  echo "── 1. create managed repo (idempotent-ish: 409 is fine)"
  curl -fsS -X POST "$A/repos" "${H_A[@]}" "${J[@]}" \
    -d '{"repositoryName":"dsh-smoke","source":{"type":"empty"},"placement":{"mode":"local"}}' \
    > /tmp/dsh-smoke-repo.json || curl -fsS "$A/repos" "${H_A[@]}" > /tmp/dsh-smoke-repo.json
  repo=$(jq -r '.repo.repoId // .repository.id // .id // empty' /tmp/dsh-smoke-repo.json)
  if [ -z "$repo" ]; then # 409 path: the POST failed, the fallback saved the LIST endpoint
    repo=$(jq -r '[.repos[]? // .repositories[]? | select(.repositoryName=="dsh-smoke" or .name=="dsh-smoke") | .repoId // .id][0] // empty' /tmp/dsh-smoke-repo.json)
  fi
  [ -n "$repo" ] || { echo "could not resolve repo id from: $(cat /tmp/dsh-smoke-repo.json)"; exit 1; }
  echo "   repo: $repo"
  echo "── 2. writable workspace on main"
  curl -fsS -X POST "$A/repos/$repo/workspaces" "${H_A[@]}" "${J[@]}" \
    -d '{"baseRef":"refs/heads/main","branchName":"refs/heads/main","mode":"writable","ttlSeconds":600}' \
    | tee /tmp/dsh-smoke-ws.json | jq . > /dev/null
  ws=$(jq -r '.workspaceId // .workspace.id' /tmp/dsh-smoke-ws.json); echo "   workspace: $ws"
  echo "── 3. write a file"
  curl -fsS -X PUT "$A/workspaces/$ws/files?path=chapters/KEY/sess-1/001-smoke.md" "${H_A[@]}" "${J[@]}" \
    -d '{"encoding":"utf8","content":"---\ntitle: \"smoke\"\n---\n# smoke\n\nhello from dsh-chapters\n"}' | jq -c . > /dev/null && echo "   ok"
  echo "── 4. commit"
  curl -fsS -X POST "$A/workspaces/$ws/commit" "${H_A[@]}" "${J[@]}" \
    -d '{"message":"dsh-chapters smoke commit","author":{"name":"dsh-chapters","email":"smoke@dsh-chapters.local"}}' \
    | tee /tmp/dsh-smoke-commit.json | jq . > /dev/null
  sha=$(jq -r '.commitSha // .commit.sha // .commit // empty' /tmp/dsh-smoke-commit.json); echo "   commit: $sha"
  echo "── 5. read back (repo query path)"
  curl -fsS -X POST "$A/repos/$repo/files/read" "${H_A[@]}" "${J[@]}" \
    -d '{"ref":"refs/heads/main","path":"chapters/KEY/sess-1/001-smoke.md","parseFrontmatter":true}' \
    | jq -c '{path: (.file.path // .document.path), title: (.file.frontmatter.title // .document.frontmatter.title)}' || jq -c . < /dev/null
  echo "── 6. list paths"
  curl -fsS -X POST "$A/repos/$repo/paths/list" "${H_A[@]}" "${J[@]}" \
    -d '{"ref":"refs/heads/main","paths":["chapters/**"],"extensions":[".md"]}' | jq -c .
  echo "smoke done. Shapes observed above are what src/treedx/provider.ts codes against; the"
  echo "exact keys are pinned live by tests/integration/treedx-live.test.ts."
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down "$@" ;;
  status) cmd_status ;;
  token) cmd_token ;;
  smoke) cmd_smoke ;;
  logs) preflight; compose logs -f treedx-api ;;
  *) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
